const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const{WebSocketServer}=require('ws');
const PORT=Number(process.env.PORT||8080),PUBLIC=path.join(__dirname,'public'),rooms=new Map();
const CH={dasher:{hp:100,s:280,cd:8000},tank:{hp:150,s:190,cd:12000},trickster:{hp:100,s:260,cd:14000},gravity:{hp:110,s:220,cd:15000},frost:{hp:105,s:230,cd:13000},shock:{hp:105,s:240,cd:10000}};
const EV=['LOW GRAVITY','SPEED CHAOS','BLACKOUT','FALLING OBJECTS','SAFE ZONE','CHAOS RAIN','POWER-UP RUSH','GRAVITY FLIP'],PU=['SPEED','SHIELD','HEAL','MAGNET','BLAST','TELEPORT','FREEZE','DOUBLE'],AR=['NEON CORE','LOST TEMPLE','SKY FACTORY'];
const uid=()=>crypto.randomBytes(7).toString('hex'),code=()=>{let c;do c=crypto.randomBytes(3).toString('hex').toUpperCase();while(rooms.has(c));return c},cl=(v,a,b)=>Math.max(a,Math.min(b,v)),d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function player(ws,n,ch,col){const c=CH[ch]||CH.dasher;return{id:uid(),ws,name:String(n||'Player').replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,16)||'Player',char:CH[ch]?ch:'dasher',color:col||'#5ee7ff',x:600,y:400,hp:c.hp,maxHp:c.hp,alive:true,ready:false,shield:0,slow:0,boost:0,double:0,inv:0,cooldown:0,elims:0,damage:0,powerups:0,input:{x:0,y:0},connected:true}}
function pub(p){return{id:p.id,name:p.name,char:p.char,color:p.color,x:p.x,y:p.y,hp:p.hp,maxHp:p.maxHp,alive:p.alive,shield:p.shield,cooldown:p.cooldown,elims:p.elims,damage:p.damage,connected:p.connected}}
function send(r,m){const s=JSON.stringify(m);for(const p of r.players.values())if(p.ws.readyState===1)p.ws.send(s)}
function snap(r){return{type:'state',hostId:r.hostId,phase:r.phase,room:r.code,arena:r.arena,timer:Math.max(0,Math.ceil((r.end-Date.now())/1000)),event:r.event,powerups:[...r.pu.values()],players:[...r.players.values()].map(pub)}}
function spawn(r,p){const others=[...r.players.values()].filter(x=>x!==p&&x.alive);for(let i=0;i<40;i++){const a=Math.random()*Math.PI*2,rad=170+Math.random()*400,x=600+Math.cos(a)*rad,y=400+Math.sin(a)*rad;if(others.every(o=>Math.hypot(o.x-x,o.y-y)>130)){p.x=x;p.y=y;return}}p.x=600;p.y=400}
function hurt(r,t,n,s){if(!t.alive||t.inv>0)return;let z=n;if(t.shield>0){const a=Math.min(t.shield,z);t.shield-=a;z-=a}if(z<=0)return;t.hp=cl(t.hp-z,0,t.maxHp);if(s)s.damage+=z;if(t.hp<=0){t.alive=false;if(s&&s!==t)s.elims++;const a=[...r.players.values()].filter(x=>x.alive);send(r,{type:'eliminated',id:t.id});if(a.length===1)end(r,a[0])}}
function ability(r,p){if(r.phase!=='playing'||!p.alive||p.cooldown>0)return;const now=Date.now(),c=CH[p.char];p.cooldown=c.cd;const ix=p.input.x,iy=p.input.y;if(p.char==='dasher'){p.inv=700;p.x=cl(p.x+ix*190,35,1165);p.y=cl(p.y+iy*190,35,765)}else if(p.char==='tank'){p.shield=60;for(const o of r.players.values())if(o!==p&&o.alive&&d(p,o)<135){hurt(r,o,10,p);push(o,p,105)}}else if(p.char==='trickster'){p.decoy=now+3500}else if(p.char==='gravity'){p.pulse=now+4500}else if(p.char==='frost'){for(const o of r.players.values())if(o!==p&&o.alive&&d(p,o)<190)o.slow=now+4000}else if(p.char==='shock'){for(const o of r.players.values())if(o!==p&&o.alive&&d(p,o)<220){hurt(r,o,p.double>now?34:24,p);break}}}
function push(o,p,n){const z=Math.max(1,d(o,p));o.x=cl(o.x+(o.x-p.x)/z*n,35,1165);o.y=cl(o.y+(o.y-p.y)/z*n,35,765)}
function pickup(r,p,u){p.powerups++;const now=Date.now();if(u.type==='SPEED')p.boost=now+7000;else if(u.type==='SHIELD')p.shield=55;else if(u.type==='HEAL')p.hp=cl(p.hp+35,0,p.maxHp);else if(u.type==='MAGNET')p.magnet=now+7000;else if(u.type==='BLAST')for(const o of r.players.values())if(o!==p&&o.alive&&d(p,o)<150){hurt(r,o,12,p);push(o,p,130)}else if(u.type==='TELEPORT')spawn(r,p);else if(u.type==='FREEZE')for(const o of r.players.values())if(o!==p&&o.alive&&d(p,o)<170)o.slow=now+2500;else if(u.type==='DOUBLE')p.double=now+8000}
function addPU(r,n=1){for(let i=0;i<n;i++){const id=uid();r.pu.set(id,{id,type:PU[Math.floor(Math.random()*PU.length)],x:70+Math.random()*1060,y:70+Math.random()*660,ttl:Date.now()+16000})}}
function start(r){r.phase='countdown';r.count=Date.now()+3500;r.arena=AR[Math.floor(Math.random()*AR.length)];r.event=null;r.pu.clear();for(const p of r.players.values()){Object.assign(p,{alive:true,hp:p.maxHp,shield:0,slow:0,boost:0,double:0,inv:2500,cooldown:0,elims:0,damage:0,powerups:0});spawn(r,p)}send(r,{type:'countdown'})}
function end(r,w){r.phase='results';r.winner=w||null;r.end=Date.now()+1200;send(r,{type:'matchEnd',winner:w?pub(w):null})}
function tick(r,dt){const now=Date.now();if(r.phase==='countdown'&&now>=r.count){r.phase='playing';r.end=now+300000;r.eventAt=now+10000;send(r,{type:'start',arena:r.arena})}if(r.phase!=='playing')return;if(now>=r.end){const a=[...r.players.values()].filter(p=>p.alive).sort((x,y)=>y.hp-x.hp||y.damage-x.damage);return end(r,a[0])}if(now>=r.eventAt){const name=EV[Math.floor(Math.random()*EV.length)];r.event={name,endsAt:now+(name==='REVERSE CONTROLS'?4000:9000)};r.eventAt=now+22000;send(r,{type:'eventWarning',name});if(name==='POWER-UP RUSH')addPU(r,8)}for(const p of r.players.values()){if(!p.alive)continue;p.cooldown=Math.max(0,p.cooldown-dt);p.inv=Math.max(0,p.inv-dt);const c=CH[p.char],slow=p.slow>now?.5:1,boost=p.boost>now?1.35:1,ev=r.event?.name;let m=slow*boost*(ev==='SPEED CHAOS'?1.45:1);p.x=cl(p.x+p.input.x*c.s*m*dt/1000,35,1165);p.y=cl(p.y+p.input.y*c.s*m*dt/1000,35,765);if(ev==='SAFE ZONE'&&Math.hypot(p.x-600,p.y-400)>330)hurt(r,p,5*dt/1000);for(const[id,u]of r.pu){if(u.ttl<now){r.pu.delete(id);continue}if(d(p,u)<30){r.pu.delete(id);pickup(r,p,u)}}}}
function handle(ws,m){let r=ws.room;if(m.type==='create'){r={code:code(),hostId:null,players:new Map(),phase:'lobby',arena:'NEON CORE',pu:new Map(),event:null,end:0,eventAt:0};rooms.set(r.code,r);const p=player(ws,m.name,m.char,m.color);r.players.set(p.id,p);r.hostId=p.id;ws.room=r;ws.player=p;ws.send(JSON.stringify({type:'joined',playerId:p.id,room:r.code,host:true}));return send(r,snap(r))}if(m.type==='join'){r=rooms.get(String(m.room||'').toUpperCase());if(!r)return ws.send(JSON.stringify({type:'error',message:'ROOM NOT FOUND'}));if(r.players.size>=8)return ws.send(JSON.stringify({type:'error',message:'ROOM FULL'}));if(r.phase!=='lobby')return ws.send(JSON.stringify({type:'error',message:'MATCH ALREADY STARTED'}));const p=player(ws,m.name,m.char,m.color);r.players.set(p.id,p);ws.room=r;ws.player=p;ws.send(JSON.stringify({type:'joined',playerId:p.id,room:r.code,host:false}));return send(r,snap(r))}if(!r||!ws.player)return;const p=ws.player;if(m.type==='ready'){p.ready=!!m.value;send(r,snap(r))}else if(m.type==='input'){p.input={x:cl(Number(m.x)||0,-1,1),y:cl(Number(m.y)||0,-1,1)}}else if(m.type==='ability')ability(r,p);else if(m.type==='start'&&r.hostId===p.id&&r.players.size>=2&&[...r.players.values()].filter(x=>x.ready).length>=2)start(r)}
const server=http.createServer((q,s)=>{let f=q.url==='/'?'/index.html':q.url.split('?')[0];f=path.normalize(f).replace(/^\.\.[\\/]/,'');const file=path.join(PUBLIC,f);fs.readFile(file,(e,b)=>{if(e){s.writeHead(404);return s.end('Not found')}const t={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[path.extname(file)]||'application/octet-stream';s.writeHead(200,{'Content-Type':t,'Cache-Control':'no-cache'});s.end(b)})});
const wss=new WebSocketServer({server});wss.on('connection',ws=>{ws.on('message',x=>{try{handle(ws,JSON.parse(x))}catch(e){ws.send(JSON.stringify({type:'error',message:'BAD MESSAGE'}))}});ws.on('close',()=>{const r=ws.room,p=ws.player;if(!r||!p)return;p.connected=false;p.input={x:0,y:0};if(r.hostId===p.id){const n=[...r.players.values()].find(x=>x.id!==p.id);r.hostId=n?.id||null}if(r.phase==='lobby')r.players.delete(p.id);else if(r.phase==='playing')setTimeout(()=>{if(!p.connected)p.alive=false},15000);send(r,snap(r))})});
setInterval(()=>{for(const r of rooms.values()){tick(r,50);if(r.phase==='playing')send(r,snap(r));if(r.phase==='results'&&Date.now()>r.end){r.phase='lobby';r.winner=null;r.event=null;for(const p of r.players.values())p.ready=false;send(r,snap(r))}if(!r.players.size)rooms.delete(r.code)}},50);
server.listen(PORT,()=>console.log('CHAOS ARENA on '+PORT));